### ISSUE TITLE
what's the overlap probability mean?

### ISSUE THREAD

**Issue by kaikai-sk** [anamabo/Predicting_failure_hard_disks#1]
def overlap_superiority(self, dist1, dist2):
        control_sample= dist1
        treatment_sample= dist2
        thresh = (control_sample.mean() + treatment_sample.mean()) / 2
        control_above= sum(control_sample>thresh)/len(control_sample)
        treatment_below= sum(treatment_sample <thresh)/ len(treatment_sample)
        overlap= control_above+ treatment_below
        superiority= np.size([x for x,y in zip(treatment_sample, control_sample) if x>y ])/len(treatment_sample)
        return overlap, superiority

what's the mean of this code??

**Comment by anamabo** [comment]
Hi Kaikai:

This code is just to evaluate how overlapped are two functions. This might give you an idea of similarity between two distributions; although a similarity test is mush better.

**Comment by kaikai-sk** [comment]
I have another question. I think you use the last day's data for every disk. I think this have problem. this can not predict failure in advance

**Comment by anamabo** [comment]
But I didn't use time series analysis. I built a model using all the data from 2015 and predict failure on data from the first week of 2016. I compared my predictions with real observations on that time period. Is something wrong in this reasoning?

**Comment by kaikai-sk** [comment]
1. My knowledge of statistics is poor！ Can you provides some info to learn cohen‘s distance better？this is what I do not understand.  Thanks very much. 
2. I think you use one day's data for every data,not a whole year. 
    And for Example : a disk disk1.  the status of disk1 in 2016's first week
          Failure            Predict                       PredictResult
1         0                       0                                     true
2         0                       1                                  true?false?
3         0                       1
...
7         1                        1                                          true

**Comment by anamabo** [comment]
1. You can find several links on the internet. Here are some:
https://en.wikiversity.org/wiki/Cohen%27s_d
http://www.statisticshowto.com/cohens-d/

2. This is a classification problem, where you have true positives, true negatives (these are correct predictions) and false negatives, false positives (misclassifications). For more information on this, you can search for confusion matrix -> https://en.wikipedia.org/wiki/Confusion_matrix
